name: mask
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  file_selector: ^1.0.0
  flutter:
    sdk: flutter
  hotkey_manager: ^0.1.7
  menu_bar: ^0.5.3
  provider: ^6.0.5
  screenshot: ^2.1.0
  super_context_menu: ^0.5.0
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
